[tool.poetry]
name = "mod-rspy"
version = "0.1.0"
description = ""
authors = ["gbPagano <guilhermebpagano@gmail.com>"]
readme = "README.md"
packages = [{include = "mod_rspy"}]

[tool.poetry.dependencies]
python = "^3.10"
maturin = "^0.15.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
